jobs:
 - name: scala-test
   type: runSh
   steps:
     - TASK:
         runtime:
           options:
             imageName: "drydock/u16scaall"
             imageTag: master
         script:
           - /usr/local/scala-2.12.5/bin/scala -version
           - /usr/local/scala-2.11.12/bin/scala -version
           - /usr/local/scala-2.10.7/bin/scala -version 

          
